# Generated by Django 4.2.16 on 2026-06-24 01:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'allergenes',
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Creneau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
            ],
            options={
                'db_table': 'creneaux',
            },
        ),
        migrations.CreateModel(
            name='MenuJour',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_menu', models.DateField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite_disponible', models.IntegerField(default=50)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('epuise', 'Épuisé')], default='disponible', max_length=15)),
            ],
            options={
                'db_table': 'menus_jour',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('poste', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('employe', 'Employé'), ('cuisinier', 'Cuisinier'), ('gestionnaire', 'Gestionnaire'), ('administrateur', 'Administrateur')], default='employe', max_length=15)),
                ('solde', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('mode_paiement', models.CharField(choices=[('solde', 'Sur solde'), ('facture', 'Facture mensuelle')], default='facture', max_length=15)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_service', models.CharField(choices=[('sur_place', 'Sur place'), ('emporter', 'À emporter'), ('livraison', 'Livraison au bureau')], default='sur_place', max_length=15)),
                ('lieu_livraison', models.CharField(blank=True, max_length=255, null=True)),
                ('options_personnalisation', models.TextField(blank=True, null=True)),
                ('code_qr', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('prepare', 'Préparé'), ('consomme', 'Consommé/Livré'), ('annule', 'Annulé')], default='en_attente', max_length=15)),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('creneau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.creneau')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='api.user')),
                ('menu_jour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='api.menujour')),
            ],
            options={
                'db_table': 'reservations',
            },
        ),
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='plats/')),
                ('type_plat', models.CharField(choices=[('entree', 'Entrée'), ('plat', 'Plat Principal'), ('dessert', 'Dessert'), ('boisson', 'Boisson')], default='plat', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allergenes', models.ManyToManyField(blank=True, related_name='plats', to='api.allergene')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plats', to='api.categorie')),
            ],
            options={
                'db_table': 'plats',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.user')),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.AddField(
            model_name='menujour',
            name='cuisinier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus_prepares', to='api.user'),
        ),
        migrations.AddField(
            model_name='menujour',
            name='plat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus_jour', to='api.plat'),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_evaluation', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plat')),
            ],
            options={
                'db_table': 'evaluations',
            },
        ),
    ]
